#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v4
# autospec commit: e738c511eb94
#
Name     : sip
Version  : 6.8.3
Release  : 47
URL      : https://files.pythonhosted.org/packages/99/85/261c41cc709f65d5b87669f42e502d05cc544c24884121bc594ab0329d8e/sip-6.8.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/99/85/261c41cc709f65d5b87669f42e502d05cc544c24884121bc594ab0329d8e/sip-6.8.3.tar.gz
Summary  : A Python bindings generator for C/C++ libraries
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: sip-bin = %{version}-%{release}
Requires: sip-license = %{version}-%{release}
Requires: sip-python = %{version}-%{release}
Requires: sip-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qscintilla
BuildRequires : qscintilla-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-configure-to-generate-Makefile.patch

%description
=========================================================
        
        What is SIP?
        ------------
        
        One of the features of Python that makes it so powerful is the ability to take
        existing libraries, written in C or C++, and make them available as Python
        extension modules.  Such extension modules are often called bindings for the
        library.
        
        SIP is a collection of tools that makes it very easy to create Python bindings
        for C and C++ libraries.  It was originally developed in 1998 to create PyQt,
        the Python bindings for the Qt toolkit, but can be used to create bindings for
        any C or C++ library.  For example it is also used to generate wxPython, the
        Python bindings for wxWidgets.
        
        SIP comprises a set of build tools and a sip module. The build tools process a
        set of specification files and generates C or C++ code which is then compiled
        to create the bindings extension module.  Several extension modules may be
        installed in the same Python package.  Extension modules can be built so that
        they are are independent of the version of Python being used.  In other words a
        wheel created from them can be installed with any version of Python starting
        with v3.8.
        
        The specification files contain a description of the interface of the C or C++
        library, i.e. the classes, methods, functions and variables.  The format of a
        specification file is almost identical to a C or C++ header file, so much so
        that the easiest way of creating a specification file is to edit a copy of the
        corresponding header file.
        
        The sip module provides support functions to the automatically generated
        code.  The sip module is installed as part of the same Python package as the
        generated extension modules.  Unlike the extension modules the sip module is
        specific to a particular version of Python (e.g. v3.8, v3.9, v3.10, v3.11).
        
        SIP makes it easy to exploit existing C or C++ libraries in a productive
        interpretive programming environment.  SIP also makes it easy to take a Python
        application (maybe a prototype) and selectively implement parts of the
        application (maybe for performance reasons) in C or C++.
        
        
        Author
        ------
        
        SIP is copyright (c) Riverbank Computing Limited.  Its homepage is

%package bin
Summary: bin components for the sip package.
Group: Binaries
Requires: sip-license = %{version}-%{release}

%description bin
bin components for the sip package.


%package license
Summary: license components for the sip package.
Group: Default

%description license
license components for the sip package.


%package python
Summary: python components for the sip package.
Group: Default
Requires: sip-python3 = %{version}-%{release}

%description python
python components for the sip package.


%package python3
Summary: python3 components for the sip package.
Group: Default
Requires: python3-core
Provides: pypi(sip)
Requires: pypi(packaging)
Requires: pypi(setuptools)
Requires: pypi(toml)
Provides: pypi(sip)

%description python3
python3 components for the sip package.


%prep
%setup -q -n sip-6.8.3
cd %{_builddir}/sip-6.8.3
%patch -P 1 -p1
pushd ..
cp -a sip-6.8.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1708991205
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sip
cp %{_builddir}/sip-%{version}/LICENSE-GPL2 %{buildroot}/usr/share/package-licenses/sip/2136dbc93e95a70deae070e44ff6b2702ec1599c || :
cp %{_builddir}/sip-%{version}/LICENSE-GPL3 %{buildroot}/usr/share/package-licenses/sip/34e9b06e7f12eaed676f57481de931ec91c6ce0a || :
cp %{_builddir}/sip-%{version}/sipbuild/module/source/12/LICENSE-GPL2 %{buildroot}/usr/share/package-licenses/sip/2136dbc93e95a70deae070e44ff6b2702ec1599c || :
cp %{_builddir}/sip-%{version}/sipbuild/module/source/12/LICENSE-GPL3 %{buildroot}/usr/share/package-licenses/sip/34e9b06e7f12eaed676f57481de931ec91c6ce0a || :
cp %{_builddir}/sip-%{version}/sipbuild/module/source/13/LICENSE-GPL2 %{buildroot}/usr/share/package-licenses/sip/2136dbc93e95a70deae070e44ff6b2702ec1599c || :
cp %{_builddir}/sip-%{version}/sipbuild/module/source/13/LICENSE-GPL3 %{buildroot}/usr/share/package-licenses/sip/34e9b06e7f12eaed676f57481de931ec91c6ce0a || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sip-build
/usr/bin/sip-distinfo
/usr/bin/sip-install
/usr/bin/sip-module
/usr/bin/sip-sdist
/usr/bin/sip-wheel

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sip/2136dbc93e95a70deae070e44ff6b2702ec1599c
/usr/share/package-licenses/sip/34e9b06e7f12eaed676f57481de931ec91c6ce0a

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
